export interface RsvpResponse {
  text: string;
  emoji: string;
}

export const IN_RESPONSES: RsvpResponse[] = [
  { text: "I knew I could trust you 🤝", emoji: "🤝" },
  { text: "YESSS! That's what I'm talking about!", emoji: "🙌" },
  { text: "My day just got better.", emoji: "✨" },
  { text: "Ride or die, baby.", emoji: "🔥" },
  { text: "Okay OKAY we're doing this!", emoji: "🚀" },
  { text: "Finally someone with taste.", emoji: "💅" },
  { text: "You absolute legend.", emoji: "👑" },
  { text: "I had a feeling about you.", emoji: "🫵" },
  { text: "The group chat is gonna go crazy.", emoji: "📲" },
  { text: "You just made the right call.", emoji: "✅" },
  { text: "Let's GET IT.", emoji: "💥" },
  { text: "We were always doing this. You just confirmed it.", emoji: "😏" },
  { text: "There's the one. There they are.", emoji: "🫶" },
  { text: "No notes. Perfect decision.", emoji: "📋" },
  { text: "You're the reason I believe in people.", emoji: "🥹" },
  { text: "Bold. Correct. Iconic.", emoji: "🎯" },
  { text: "The vibes are immaculate.", emoji: "🌊" },
  { text: "You had me at 'I'm in.'", emoji: "❤️" },
  { text: "That's my person right there.", emoji: "👆" },
  { text: "History will remember this moment.", emoji: "📜" },
  { text: "We are SO back.", emoji: "🔄" },
  { text: "Chills. Literal chills.", emoji: "🥶" },
  { text: "This is exactly what I needed.", emoji: "💯" },
  { text: "You just unlocked something.", emoji: "🔓" },
  { text: "MVP behavior. Truly.", emoji: "🏆" },
  { text: "The prophecy has been fulfilled.", emoji: "🔮" },
  { text: "Textbook. Absolutely textbook.", emoji: "📖" },
  { text: "You didn't hesitate. Respect.", emoji: "🫡" },
  { text: "We eat so good.", emoji: "🍽️" },
  { text: "A star is born.", emoji: "⭐" },
  { text: "I'd pick you first every time.", emoji: "🙋" },
  { text: "Knew you had it in you.", emoji: "💪" },
  { text: "The homie has ARRIVED.", emoji: "🎉" },
  { text: "Put some respect on that decision.", emoji: "🖐️" },
  { text: "That's a ten. A hard ten.", emoji: "🔟" },
  { text: "Built different. You just proved it.", emoji: "🏗️" },
  { text: "Not me crying in the club rn.", emoji: "😭" },
  { text: "OK superstar, let's go!", emoji: "🌟" },
  { text: "Every great crew needs someone like you.", emoji: "🫂" },
  { text: "Confirmed. You are the moment.", emoji: "📸" },
  { text: "Squad status: SECURED.", emoji: "🔐" },
  { text: "That just went from a 7 to a 10.", emoji: "📈" },
  { text: "Honestly? Didn't even need to ask.", emoji: "😎" },
  { text: "You are the answer to a prayer.", emoji: "🙏" },
  { text: "Ohhhh it's happening.", emoji: "👀" },
  { text: "You're the glue. You always were.", emoji: "🪄" },
  { text: "No cap, you're the GOAT.", emoji: "🐐" },
  { text: "Breaking news: good decision made.", emoji: "📰" },
  { text: "Certified W.", emoji: "🏅" },
  { text: "And THAT is why you're my favorite.", emoji: "💛" },
];

export const OUT_RESPONSES: RsvpResponse[] = [
  { text: "Bruhhhh… 😔", emoji: "😔" },
  { text: "Wow. Just… wow.", emoji: "🙃" },
  { text: "I'll remember this.", emoji: "👁️" },
  { text: "Et tu, Brute?", emoji: "🗡️" },
  { text: "The betrayal is real.", emoji: "💔" },
  { text: "Okay. Okay. I'm fine. I'm totally fine.", emoji: "😶" },
  { text: "We're putting your name in the group chat anyway.", emoji: "📲" },
  { text: "Not even a little? A little??", emoji: "🥺" },
  { text: "Your loss. Genuinely.", emoji: "🚪" },
  { text: "This is why I have trust issues.", emoji: "😤" },
  { text: "The audacity is breathtaking.", emoji: "😮" },
  { text: "Cool. Cool cool cool.", emoji: "🆒" },
  { text: "I hope you think about what you did.", emoji: "⌛" },
  { text: "Must be nice. Saying no like that.", emoji: "😑" },
  { text: "I've already moved on. (I haven't.)", emoji: "🏃" },
  { text: "Noted. Filed. Never forgotten.", emoji: "🗂️" },
  { text: "My therapist is gonna hear about this.", emoji: "🛋️" },
  { text: "Fine. I'll go with Derek then.", emoji: "🙄" },
  { text: "You are COOKED in the next group activity.", emoji: "🍳" },
  { text: "On behalf of the group: seriously?", emoji: "😒" },
  { text: "The weakest link has been identified.", emoji: "🔗" },
  { text: "Didn't want you anyway. (Yes I did.)", emoji: "😩" },
  { text: "A crime has been committed today.", emoji: "🚨" },
  { text: "This is giving 'I can't, I have plans' energy.", emoji: "📆" },
  { text: "You were my first call. My FIRST call.", emoji: "📞" },
  { text: "The history books will not be kind.", emoji: "📜" },
  { text: "I accept this. Under protest.", emoji: "✍️" },
  { text: "You've made an enemy of fun.", emoji: "😠" },
  { text: "Somewhere a puppy is sad.", emoji: "🐶" },
  { text: "Wow okay so we're doing this then.", emoji: "😤" },
  { text: "I'm logging this as an L.", emoji: "📉" },
  { text: "You're missing out on peak activity.", emoji: "🎢" },
  { text: "I am SHOOK. Shooketh, even.", emoji: "😳" },
  { text: "The villain arc begins now.", emoji: "😈" },
  { text: "I'll send you a postcard from the fun.", emoji: "💌" },
  { text: "Unsubscribed from your energy.", emoji: "🔕" },
  { text: "We're sending a search party later.", emoji: "🔦" },
  { text: "This is being archived as a red flag.", emoji: "🚩" },
  { text: "Do you even know what you've done?", emoji: "🤦" },
  { text: "That's okay. Karma knows your address.", emoji: "📍" },
  { text: "I'm going to pretend I didn't see this.", emoji: "🙈" },
  { text: "You had ONE job.", emoji: "☝️" },
  { text: "Next time we're not even asking you.", emoji: "✂️" },
  { text: "This is a certified bruh moment.", emoji: "📋" },
  { text: "The group has been notified of your absence.", emoji: "📣" },
  { text: "Respectfully… reconsider.", emoji: "🙏" },
  { text: "You're dead to me. (Temporarily.)", emoji: "⚰️" },
  { text: "We'll minute-by-minute update you on the fun.", emoji: "⏱️" },
  { text: "Unreal. Absolutely unreal.", emoji: "🤯" },
  { text: "Big mistake. Huge.", emoji: "🏬" },
];

export const getRandomRsvpResponse = (status: 'in' | 'out'): RsvpResponse => {
  const list = status === 'in' ? IN_RESPONSES : OUT_RESPONSES;
  return list[Math.floor(Math.random() * list.length)];
};
